Add Global ID (and larger boundary conditions)
SeisSol/SeisSol pull request #1039
Opened 2024-02-06 16:52 UTC by davschneller

Adds a global ID to each element (in preparation to checkpointing). Also, we streamline 64-bit boundary conditions.

Dependent on the PUML2 PR https://github.com/TUM-I5/PUML2/pull/14 .

2024-02-29 08:21 UTC, Thomas-Ulrich requested changes

2024-02-29 08:21 UTC, Thomas-Ulrich commented on src/Geometry/PUMLReader.cpp
> +    return true;
I would also return error in this case.

2024-02-29 08:21 UTC, Thomas-Ulrich commented on src/Geometry/PUMLReader.cpp
>   * @todo Cleanup this code
still required?

2024-02-29 08:21 UTC, Thomas-Ulrich commented on src/Geometry/PUMLReader.cpp
> +const int FaceVertexToOrientation[4][4] = {
can you add a comment about what is orientation?

2024-02-29 08:21 UTC, Thomas-Ulrich commented on src/Geometry/PUMLReader.cpp
> +const int FirstFaceVertex[4] = {0, 0, 0, 1};
can you add a comment about what it is?

2024-02-29 08:21 UTC, Thomas-Ulrich commented on src/Geometry/PUMLReader.h
> +#include <Initializer/Parameters/MeshParameters.h>
shouldn't it be "Initializer/Parameters/MeshParameters.h"?

2024-03-14 15:02 UTC, davschneller commented
Ok; I've added an `auto` option which checks the HDF5 file. (if we ever should add bare-binary Xdmf support or Hdf5 data from different files, we may need to read the XML file instead)

2024-03-16 19:58 UTC, palgunadi1993 commented
I tested this PR. It works fine with my fracture network model. Thanks @davschneller !

2024-03-20 08:33 UTC, Thomas-Ulrich approved these changes

2024-03-21 10:01 UTC, merged