Create get_nuc_stress_tensor.py
SeisSol/SeisSol pull request #1095
Opened 2024-04-11 22:26 UTC by jwjeremy

@AliceGabriel 
A simple Python script to compute stress tensor (potentially useful for nucleation stress) given fault geometry and stress level

2024-05-17 11:48 UTC, Thomas-Ulrich requested changes
Thank you for this PR (and for noticing what was the problem with the nucleation stress in the Kaikoura and Palu setups).
But is it not  simpler to use Tnuc_s and Tnuc_d?
```yaml
!Switch
[Tnuc_n,Tnuc_s,Tnuc_d]: !LuaMap
  returns: [Tnuc_n,Tnuc_s,Tnuc_d]
  function: |
     function f (x)
      ShapeNucleation = 0.0
      xh =  -3581
      yh = -29146
      zh = -10000
      -- rake in SeisSol convention
      rake = 30 * math.pi/180
      r_crit = 1500.0
      r = math.sqrt((x["x"]-xh)^2 + (x["y"]-yh)^2 + (x["z"]-zh)^2 )
      if (r < r_crit) then
        peakNucleationStress =  math.exp(r^2/(r^2-r_crit^2))*20*math.pow(10,6)
      end
      return {
        Tnuc_n = 0.0,
        Tnuc_d =  peakNucleationStress*sin(rake),
        Tnuc_s = peakNucleationStress*cos(rake)
      }
      end
```
(or you can replace 20 by R_nuc*(fs - fd)*Pn0 + fd*Pn0)

2024-05-17 11:48 UTC, Thomas-Ulrich commented on preprocessing/science/get_nuc_stress_tensor.py
> +if args.R_nuc is None:
if not args.R_nuc
(try flake8 on your script)

2024-05-17 11:48 UTC, Thomas-Ulrich commented on preprocessing/science/get_nuc_stress_tensor.py
> +Ts0 = T0 * np.cos(np.deg2rad(rake))
Note that rake must be in seissol convention.
(e.g. adapted from Slipnear: "rake" (degrees) is the slip angle (not Aki's convention, e.g. rake=+45 means right-lateral-reverse movement).

2024-05-17 11:48 UTC, Thomas-Ulrich commented on preprocessing/science/get_nuc_stress_tensor.py
> +    T0 = R_nuc*(fs - fd)*Pn0 + fd*Pn0
Pn0 should be positive?

2024-05-17 11:48 UTC, Thomas-Ulrich commented on preprocessing/science/get_nuc_stress_tensor.py
> +      xc = -18440.7
maybe leave empty?
same for xc, yc, r_crit?

2024-05-17 11:48 UTC, Thomas-Ulrich commented on preprocessing/science/get_nuc_stress_tensor.py
> +        nuc_xx = ShapeNucleation * {S_cartesian[0,0]:.3f} * 1000000;
put the 1000000 in ShapeNucleation?

2024-06-04 16:00 UTC, jwjeremy commented
Thanks @Thomas-Ulrich for the edits! I initially thought nuc_ij is required with initial_stress tensor.

2024-06-04 16:01 UTC, jwjeremy commented on preprocessing/science/get_nuc_stress_tensor.py
> +    epilog="Examples: \npython get_nuc_stresstensor.py --geometry 9.58 202.27 90  --Traction -18.82 --yaml \npython get_nuc_stresstensor.py --geometry 9.58 202.27 90  --R_nuc 1.1 0.7 0.1 33.6",
yes agree!

2025-04-12 00:02 UTC, closed without merging