Numa optimization and pinning fixes
SeisSol/SeisSol pull request #281
Opened 2020-12-11 14:54 UTC by krenzland

- Pinning now works even when using more than 1 mpi rank/node
- Initialize DR in a NUMA-aware manner

Improves performance by a lot for R&S-FL when using 1 rank per node on NG.

(History is pretty messy)

2020-12-11 15:15 UTC, uphoffc requested changes

2020-12-11 15:15 UTC, uphoffc commented on src/Parallel/Pin.cpp
> +  return pthreadMask;
(You can ignore the following comment if you want.)

Storing pthreadMask is actually redundant as you already store processMask and openmpMask. The operation to compute pthreadMask is really cheap.

2020-12-11 15:15 UTC, uphoffc commented on src/Parallel/Pin.h
> +  cpu_set_t getPthreadMask() const { return pthreadMask; };
getPthreadMask and getFreeCPUsMask are aliases?

2020-12-11 15:15 UTC, uphoffc commented on src/SeisSol.h
> +	}
Do you intend to return a copy here? Should be ok as the object is not large.

2020-12-11 15:15 UTC, uphoffc commented on src/Solver/time_stepping/TimeManager.cpp
> +  seissol::SeisSol::main.getPinning().pinToFreeCPUs();
Same comment as above, I'd pass pinning as parameter.

2020-12-11 15:48 UTC, krenzland commented on src/Physics/ini_model_DR.f90
> +    if (EQN%FL /= 33) then !33 is ImposedSlipRateOnDRBoundary
No, apparently .NE. is deprecated

2020-12-11 15:49 UTC, krenzland commented on src/SeisSol.cpp
> +  // (Doesn't actually pin anything, yet!)
True.

2020-12-11 15:50 UTC, krenzland commented on src/Initializer/dg_setup.f90
> +      ! Initialize w/ first-touch
Not sure. The initialization is all over the code...

2020-12-11 15:51 UTC, krenzland commented on src/Checkpoint/Manager.cpp
> +    const auto freeCpus = SeisSol::main.getPinning().getFreeCPUsMask();
Sure, if you can tell me where this stuff is actually called. If I remember correctly, it's quite hidden.

2020-12-11 15:56 UTC, uphoffc commented on src/Checkpoint/Manager.cpp
> +    const auto freeCpus = SeisSol::main.getPinning().getFreeCPUsMask();
It's called by async. If you want to change it you'd need to pass pinning to the constructor. Might make sense to introduce a base class here, as the pinning code is copied & pasted as far as I could see.

2020-12-11 16:23 UTC, krenzland commented on src/Physics/ini_model_DR.f90
> +           DISC%DynRup%magnitude_out(i) = .TRUE.
I really don't want to know.

2021-01-20 13:56 UTC, uphoffc approved these changes

2021-01-20 14:50 UTC, merged