Poroelastic
SeisSol/SeisSol pull request #383
Opened 2021-08-30 12:18 UTC by sebwolf-de

Finally, the poroelasticity PR ;-)
Major changes: 
* Space-Time-Predictor to integrate the stiff source term from the poroelastic equations
* Armadillo as an alternative to eigen3, as long as https://gitlab.com/libeigen/eigen/-/issues/2305 is not fixed

2021-08-30 13:02 UTC, uphoffc commented
Why don't we use LAPACK? More likely to be installed than armadillo.

2021-08-30 13:16 UTC, sebwolf-de commented
> Why don't we use LAPACK? More likely to be installed than armadillo.

Mostly, because armadillo is easier to use. After all, armadillo is just a fancy wrapper around LAPACK: https://scicomp.stackexchange.com/a/26397
The installation is really straightforward, so this does not pose a major issue IMHO. I hope that Eigen3 will fix the accuracy issue soonish, so that we can remove armadillo again.

2021-08-30 13:33 UTC, krenzland commented
But LAPACK is available on many HPC systems as a module. This would make the installation easier.

2021-08-30 14:35 UTC, uphoffc commented
When using LAPACK, one has to be a bit careful with the symbol names. Depending on the software stack one has to prepend N >= 0 underscores in front of the LAPACK function name. Fortunately CMake supports automatic name mangling in the following way:

```cmake
check_language(Fortran)
if(CMAKE_Fortran_COMPILER)
    enable_language(Fortran)
    include(FortranCInterface)
    FortranCInterface_HEADER(FC.h MACRO_NAMESPACE "FC_")

    find_package(LAPACK)
    if(${LAPACK_FOUND})
        add_definitions(-DHAVE_LAPACK)
    endif()
endif()
```

One can then create a little header file that mangles the name, e.g.:

```c++
#ifndef LAPACK_20210208_H
#define LAPACK_20210208_H

#include "FC.h"

#define FC_dsyev FC_GLOBAL(dsyev, DSYEV)
extern void FC_dsyev(char const* jobz, char const* uplo, int const* n, double* A, int const* lda,
                     double* W, double* work, int const* lwork, int* info);

#endif // LAPACK_20210208_H
```

2021-08-30 15:00 UTC, krenzland requested changes
Hi,
looks good mostly. Didn't spot any bugs.
Two things (in addition to Armadillo) are worth discussing:
- I'm not a fan of adding parameter files (and a test runner) in src/tests, especially because we already have a test runner in our CI: https://github.com/SeisSol/Examples/tree/master/convergence_elastic
- The Time kernel is nearly a direct copy of the elastic time kernel with some differences. This is really bad code quality. We can also tackle this together when I'll begin templating the kernels.

PS: Where are your matrices? Did you already push them to the git? Only asking because I always forget that step...

2021-08-31 13:29 UTC, sebwolf-de commented on CMakeLists.txt
> +    target_compile_definitions(SeisSol-lib PUBLIC HAS_ARMADILLO)
Armadillo is only required for poroelastic materials. But indeed, this is redundant with USE_POROELASTIC

2021-08-31 13:35 UTC, sebwolf-de commented on azure-pipelines-seissol-template.yml
> +                        ./test_serial_test_suite
True, I just put this in for debugging, as make test suppresses the output.

2021-08-31 15:23 UTC, krenzland commented on CMakeLists.txt
> +    target_compile_definitions(SeisSol-lib PUBLIC HAS_ARMADILLO)
You can remove a lot of these ifdefs in the poor code - would make it easier to read

2021-09-01 10:04 UTC, sebwolf-de reviewed
Thanks for the comments, most of it should be addressed by now. I am still thinking about the LAPACK/armadillo thing...

2021-09-03 14:42 UTC, krenzland approved these changes

2021-09-03 14:46 UTC, merged