Update compilation.rst
SeisSol/SeisSol pull request #497
Opened 2022-02-24 12:55 UTC by NicoSchlw

Correct the PSpaMM symlink in the docs

2022-02-24 12:57 UTC, ravil-mobile commented
Hi, could you also mention that `pspamm` can be installed with Spack
```
spack install py-pspamm
```
it will require Spack version >=0.17.2

2022-02-24 12:57 UTC, Thomas-Ulrich commented
This won't work if bin does not exist.
What you need is mkdir ~/bin before the symbolic link.

2022-02-24 12:59 UTC, ravil-mobile commented
In general, one needs to just clone pspamm to a directory and then append `PATH` and `PYTHONPATH` with the name of that directory

2022-02-24 13:06 UTC, NicoSchlw commented
So should we just provide the lines for the bashrc in the docs?

2022-02-24 16:49 UTC, NicoSchlw commented
Is appending to PYTHONPATH really necessary?

2022-02-24 17:52 UTC, krenzland commented
Nope, never done that.

2022-02-24 17:53 UTC, krenzland requested changes

2022-02-24 17:53 UTC, krenzland commented on Documentation/compilation.rst
> +   export PATH=<Your_Path_to_PSpaMM>/PSpaMM:$PATH
This line is a bit confusing, shouldn't it be
export PATH=<Your_Path_to_PSpaMM>:$PATH
?

2022-02-25 15:36 UTC, krenzland approved these changes

2022-02-25 15:36 UTC, krenzland commented
Thanks!

2022-02-25 15:36 UTC, merged