Duo/fix tpv6
SeisSol/SeisSol pull request #596
Opened 2022-07-01 11:57 UTC by daisy20170101

I realized some small errors that have lead to the problem in tpv6. Now i have a proper rupture.

2022-07-01 11:58 UTC, daisy20170101 commented
related to 
https://github.com/SeisSol/SeisSol/discussions/590

2022-07-01 12:10 UTC, sebwolf-de approved these changes
LGTM

2022-07-01 12:13 UTC, ravil-mobile commented
@sebwolf-de , are you going to integrate it to `dr/cpp`?

2022-07-01 12:14 UTC, sebwolf-de commented
Yes

2022-07-01 13:53 UTC, Thomas-Ulrich commented
The strength should be - mud *min(0, tn0), as in other friction laws not mud* abs(tn0) 

Le 1 juillet 2022 14:10:28 GMT+02:00, Sebastian Wolf ***@***.***> a écrit :
***@***.*** approved this pull request.
>
>LGTM
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/SeisSol/SeisSol/pull/596#pullrequestreview-1026134274
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>

2022-07-04 06:54 UTC, Thomas-Ulrich commented on src/Physics/ini_model_DR.f90
> +      DISC%DynRup%Strength(iBndGP,iFace) = EQN%IniMu(iBndGP,iFace) * abs(EQN%InitialStressInFaultCS(iBndGP,1,iFace))
Should it be:
```
Strength = -DISC%DynRup%cohesion(:,iFace) - DISC%DynRup%Mu(:,iFace) * MIN(EQN%InitialStressInFaultCS(iBndGP,1,iFace),ZERO)  
```?

2022-07-04 06:55 UTC, Thomas-Ulrich requested changes
see comment

2022-07-04 07:22 UTC, Thomas-Ulrich approved these changes

2022-07-04 07:22 UTC, daisy20170101 commented on src/Physics/ini_model_DR.f90
> +      DISC%DynRup%Strength(iBndGP,iFace) = EQN%IniMu(iBndGP,iFace) * abs(EQN%InitialStressInFaultCS(iBndGP,1,iFace))
Thanks Thomas!  how about now?

2022-07-07 07:04 UTC, merged