Changes requested for DR Factory:
SeisSol/SeisSol pull request #634
Opened 2022-07-28 10:00 UTC by sebwolf-de

* Remove strange comment
* Rename Products -> DynamicRuptureTuple
* Reference -> shared_ptr
* use default and override

2022-07-28 12:37 UTC, ravil-mobile commented on src/DynamicRupture/Parameters.h
> +  if (params->operator[]("elementwise")) {
Maybe `*param["elementwise"]` or `(*param)["elementwise"]`

2022-07-28 12:37 UTC, ravil-mobile commented on src/DynamicRupture/Parameters.h
> +  if (params->operator[]("pickpoint")) {
the same as above

2022-07-28 12:38 UTC, ravil-mobile commented
let me try this branch with GPU offloading

2022-07-30 00:41 UTC, ravil-mobile commented
Everything works with GPUs

2022-08-01 13:17 UTC, krenzland requested changes
Looks good to me, calling operator[] is a bit weird though. Any reason?

2022-08-01 13:17 UTC, krenzland commented on src/DynamicRupture/Parameters.h
> +  if (params->operator[]("elementwise")) {
agreed

2022-08-02 07:31 UTC, krenzland approved these changes

2022-08-02 07:31 UTC, merged