Adding animation visualization tool
SeisSol/SeisSol pull request #652
Opened 2022-08-25 21:50 UTC by jrekoske

This PR adds two Python utilities for visualization. These are particularly useful for quickly visualizing the output of small-scale simulations without having to open the output in ParaView.

1) `make_animation` creates an animation (GIF) of the free surface wave-field using a free surface output XDMF file, ex:

![anim](https://user-images.githubusercontent.com/58538930/186774592-b5426eaa-d8d2-41a2-9597-2da1e150a2b9.gif)

2) `plot_imt_map` creates a map of a ground motion intensity metric using the output from `ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py`, ex:

![pgv](https://user-images.githubusercontent.com/58538930/186775126-b0be3716-0797-4704-a879-434e788d9d61.png)

2022-08-25 22:56 UTC, jrekoske commented
`make_animation` should probably work for 2D fault output as well, though I haven't used that yet.

2022-08-26 07:06 UTC, sebwolf-de requested changes
Hi, thanks for these scripts. I think they are particularly useful, since you can easily execute them on some cluster and then just download the final image. I have a few remarks, but nothing serious.

2022-08-26 07:06 UTC, sebwolf-de commented on postprocessing/visualization/tools/make_animation.py
> +        '--bounds', nargs='+', help='xmin xmax ymin ymax', type=float)
Maybe add an option to define the output filename.

2022-08-26 07:06 UTC, sebwolf-de commented on postprocessing/visualization/tools/plot_imt_map.py
> +    plt.ylabel('Northing (m)')
This only holds for ENU meshes. I'd prefer {x, y} here, since some user might use a different coordinate system.

2022-08-26 07:06 UTC, sebwolf-de commented on postprocessing/visualization/tools/make_animation.py
> +    ax.set_ylabel('Northing (m)')
This only holds for ENU meshes. I'd prefer {x, y} here, since some user might use a different coordinate system.

2022-08-26 15:17 UTC, jrekoske commented
Thanks I made the requested changes

2022-08-26 17:09 UTC, sebwolf-de approved these changes

2022-08-29 07:28 UTC, merged