Flop Counter Improvements
SeisSol/SeisSol pull request #744
Opened 2022-11-29 16:04 UTC by sebwolf-de

* Write Flop Counter per node to csv file for detailed analysis.
* Compute current performance (since last syncpoint) instead of average since the beginning. This way you better see changes in performance.
* Better output to stdout.

2022-12-01 08:29 UTC, krenzland commented
> Compute current performance (since last syncpoint) instead of average since the beginning. This way you better see changes in performance.

Is this in addition to the old way of outputting or replacing it?

I agree that it is valuable information, however, I **need** the overall FLOPS as well. Otherwise reporting the performance of unfinished runs is impossible. This feature is really needed for full-machine runs for example.

2022-12-01 08:44 UTC, sebwolf-de commented
It's a replacement, but we can also output both.

2022-12-01 08:52 UTC, Thomas-Ulrich reviewed
Looks good. I also tested and it works.

2022-12-01 08:52 UTC, Thomas-Ulrich commented on src/Solver/Interoperability.cpp
> +  seissol::SeisSol::main.flopCounter().init(freeSurfaceFilename);
Should  it be named outputFileNamePrefix?

2022-12-01 08:52 UTC, Thomas-Ulrich commented on src/Monitoring/FlopCounter.hpp
> +  double recentWallTime = 0;
what about previousCallWallTime and previousCallTotalFlops?
or previousWallTime?

2022-12-01 08:55 UTC, krenzland commented
Yes, please do both.

2022-12-01 09:02 UTC, krenzland requested changes
LGTM
However:
GFLOP/s -> GFLOPS (standard nomenclature) 
Please output both recent and overall GFLOPS

2022-12-01 10:54 UTC, sebwolf-de commented on src/Monitoring/FlopCounter.hpp
> +class FlopCounter {
Actually, I want `previousTotalFlops` and `previousWallTime` to be private.

2022-12-01 13:57 UTC, krenzland commented on src/Monitoring/FlopCounter.hpp
> +class FlopCounter {
You can have private members in structs

2022-12-01 13:57 UTC, krenzland commented on src/Monitoring/FlopCounter.hpp
> +class FlopCounter {
Actually, struct/class are identical, the only difference is default visibility

2022-12-05 13:29 UTC, krenzland approved these changes

2022-12-05 13:29 UTC, merged