make script compatible with volume output
SeisSol/SeisSol pull request #826
Opened 2023-03-22 20:05 UTC by NicoSchlw

2023-03-23 09:22 UTC, krenzland commented
What exactly is this computing? What is the GME of a volume output?

2023-03-23 09:44 UTC, NicoSchlw commented
It might be interesting to use some of the (low-frequency) metrics of the script also for volume output. For example, I'm comparing how peak displacements and peak velocities decay with distance at the surface and at depth.

2023-06-14 11:00 UTC, NicoSchlw commented
I updated the PR based on the reviews, I liked Thomas's idea of using the shape of connect to identify volume data

2023-06-23 14:36 UTC, NicoSchlw commented on postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py
>    # Copy connect and geometry:
Yes good idea, I did it now

2023-06-23 14:47 UTC, Thomas-Ulrich requested changes
Thank you, that's much better.

2023-06-23 14:47 UTC, Thomas-Ulrich commented on postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py
> +    myres = comm.gather(myres, root=0)
oh man, my code was a shame :-)
You can remove also above:
```
h5f = h5py.File('temp'+str(irank)+'.h5','w')
for i,dname in enumerate(dataName):
     hdname = "mesh0/"+dname
     h5f.create_dataset(hdname, (nElements_i,), dtype='d')
     h5f[hdname][:] = myres[:,i]
h5f.close()
```

2023-06-23 16:08 UTC, Thomas-Ulrich approved these changes
thank you

2023-06-29 09:23 UTC, NicoSchlw commented
Hi @krenzland, can you approve this PR?

2023-06-29 10:58 UTC, krenzland approved these changes

2023-06-29 10:58 UTC, krenzland commented
Sorry, I wasn't aware that I was blocking this.

2023-06-29 11:19 UTC, merged